version: '3.1'

services:
  db:
    image: 'postgres:14.0'
    restart: always
    volumes:
      - .db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'form_website'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1'

  website:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    
