version: '3.1'

services:
  db:
    container_name: 'db'
    image: 'postgres:14.0'
    restart: always
    volumes:
      - .db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1'

  website:
    container_name: 'website'
    image: 'form-website:latest'
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

